### ISSUE TITLE
Some errors in kernel.cl

### ISSUE THREAD

**Issue by Allespro** [iIIusi0n/ed25519-gpu#1]
Hello. Trying to run your kernel code (kernel.cl). It showed some errors: wrong variable definitions.
I will attach the log below.
I tried to figure it out, as I realized a lot depends on what scope the variable is in. If you know how to fix it, I'm ready to help you.
I use MacBook Pro with Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
OpenCl 1.2
https://pastebin.com/YY4wUJ7C

**Comment by Allespro** [comment]
Solved using OpenCL 2.0 (Tesla T4)
You can have program scope or static variables in `__global` address space, but only in OpenCL 2.0. You can pass `-cl-std=CL2.0` to `clBuildProgram` to enable this, if your OpenCL implementation (a driver) have OpenCL 2.0 support.

https://stackoverflow.com/questions/50168283/opencl-variable-declaration-failed-outside-kernel-scope

**Comment by iIIusi0n** [comment]
Sorry for late because there was unpredictable accident for my body. I reviewd my code and recognize problem with your issue. Really thank you for it. Btw, it was my first use of OpenCL, so expect future project :)
